version: '2'
services:
  web:
    build:
      dockerfile: Dockerfile.backend
      context: .
    command: yarn serve
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
  redis:
    image: redis:5-alpine
    container_name: redis
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
