version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build and deploy"
          command: "bin/ci-deploy.sh"
  code_style:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "yarn install"
      - run:
          name: "Check code style"
          command: "bin/check-code-style.sh"
  deploy_to_production:

    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: "Test"
          command: "echo 'We should deploy now.'"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - code_style
      - deploy_to_production:
          requires:
            - build
            - code_style
          filters:
            branches:
              only:
                - master
                - deployment-test
