version: 2.1
jobs:
  code_style:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "yarn install"
      - run:
          name: "Check code style"
          command: "bin/check-code-style.sh"

  build_dashboard:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build backend image"
          command: "bin/build-docker-dashboard.sh"
      - run:
          name: "Push image if on master"
          command: "bin/push-docker-dashboard-image.sh"


  build_widgets:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build widgets image"
          command: "bin/build-docker-widgets.sh"


  build_backend:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build dashboard image"
          command: "bin/build-docker-backend.sh"
      - run:
          name: "Push image if on master"
          command: "bin/push-docker-backend-image.sh"

  deploy_to_production:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install envsubst
          command: apt-get install -qq -y gettext
      - run:
          name: "Deploy"
          command: "bin/ci-update-deployments.sh"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_dashboard
      - build_backend
      - build_widgets
      - code_style
      - deploy_to_production:
          requires:
            - build_dashboard
            - build_backend
            - build_widgets
            - code_style
          filters:
            branches:
              only:
                - master
