apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizzes-backend-deployment
spec:
  selector:
    matchLabels:
      app: quizzes-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: quizzes-backend
    spec:
      containers:
      - name: quizzes-backend
        image: gcr.io/moocfi/quizzes-backend
        imagePullPolicy: Always
        ports:
        - name: backend-http
          containerPort: 3000
        env:
          - name: REDIS_HOST
            value: "quizzes-backend-redis-slave.default.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quizzes-backend-redis
                key: redis-password
