apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizzes-backend-deployment
spec:
  selector:
    matchLabels:
      app: quizzes-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: quizzes-backend
    spec:
      containers:
      - name: quizzes-backend
        image: gcr.io/moocfi/quizzes-backend:build-1552303737-35a059be0f31423ba8fab293fa962eac86e869fd
        imagePullPolicy: Always
        ports:
        - name: backend-http
          containerPort: 3000
        env:
          - name: REDIS_HOST
            value: "quizzes-backend-redis-master.default.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quizzes-backend-redis
                key: redis-password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_DATABASE
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_HOST
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_USERNAME
