apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizzes-backend-deployment
spec:
  selector:
    matchLabels:
      app: quizzes-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: quizzes-backend
    spec:
      containers:
      - name: quizzes-backend
        image: gcr.io/moocfi/quizzes-backend:build-1561024103-2f80b4b65a13ebd43ff3e06dd547f10228d98cf0
        imagePullPolicy: Always
        ports:
        - name: backend-http
          containerPort: 3000
        env:
          - name: REDIS_HOST
            value: "quizzes-backend-redis-master.default.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quizzes-backend-redis
                key: redis-password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_DATABASE
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_HOST
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_USERNAME
      initContainers:
      - name: quizzes-backend-run-migrations
        image: gcr.io/moocfi/quizzes-backend:build-1561024103-2f80b4b65a13ebd43ff3e06dd547f10228d98cf0
        command: ['sh', '-c', 'cd /app && yarn typeorm migration:run']
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_DATABASE
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_HOST
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_USERNAME
