apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: create-user-quiz-states
spec:
  schedule: "3/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: create-user-quiz-states
              image: ${BACKEND_IMAGE}
              command: ["sh", "-c", "cd /app && yarn create-user-quiz-states-cron"]
              resources:
                requests:
                  memory: "2000Mi"
              env:
                - name: REDIS_HOST
                  value: "quizzes-backend-redis-master.default.svc.cluster.local"
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: quizzes-backend-redis
                      key: redis-password
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: backend-database-secret
                      key: POSTGRES_DATABASE
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: backend-database-secret
                      key: POSTGRES_HOST
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backend-database-secret
                      key: POSTGRES_PASSWORD
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: backend-database-secret
                      key: POSTGRES_USERNAME
                - name: TMC_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: backend-database-secret
                      key: TMC_TOKEN
          initContainers:
          - name: quizzes-backend-run-migrations
            image: ${BACKEND_IMAGE}
            command: ['sh', '-c', 'cd /app && yarn typeorm migration:run']
            env:
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: backend-database-secret
                    key: POSTGRES_DATABASE
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: backend-database-secret
                    key: POSTGRES_HOST
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: backend-database-secret
                    key: POSTGRES_PASSWORD
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: backend-database-secret
                    key: POSTGRES_USERNAME
