apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: quizzes-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - quizzes.mooc.fi
    secretName: quizzes-moocfi-cert-secret
  rules:
    - host: quizzes.mooc.fi
      http:
        paths:
        - path: /api/*
          backend:
            serviceName: quizzes-backend-service
            servicePort: 80
        - path: /
          backend:
            serviceName: quizzes-dashboard-service
            servicePort: 80
