apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: quizzes-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
     location /ws {
        deny all;
        return 400;
      }
spec:
  tls:
  - hosts:
    - quizzes.mooc.fi
    secretName: quizzes-cert-secret
  rules:
    - host: quizzes.mooc.fi
      http:
        paths:
        - path: /api/
          backend:
            serviceName: quizzes-backend-service
            servicePort: 80
        - path: /
          backend:
            serviceName: quizzes-dashboard-service
            servicePort: 80
