apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: quizzes-ingress
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: quizzes-backend-service
            servicePort: 80
